import { PageInfo } from "../types/index.js";

const UNSPLASH = {
  avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
  store: "https://images.unsplash.com/photo-1556745757-8d76bdb6984b?w=600",
  noodles: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600",
  oil: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600",
  warehouse: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600",
  banner: "https://images.unsplash.com/photo-1556742049-0cfed4f06a45?w=1200",
  seller: "https://images.unsplash.com/photo-1560179707-fc0cdb330363?w=200",
  vendor: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=200",
};

export const toVariantProduct = (product: Record<string, unknown>) => ({
  ...product,
  displayTitle: product.displayName || product.variantName,
  product_SKU: product.sku,
  images: { imageUrl: product.imageUrl },
  pricing: {
    wholesalePrice: Math.round(Number(product.price) * 0.9),
    retailPrice: product.price,
    marketPrice: Math.round(Number(product.price) * 1.1),
  },
  maxPurchasePrice: product.price,
});

export const demoPermissions = [
  "access_admin",
  "access_sellers_portal",
  "view_users",
  "create_users",
  "change_password",
  "view_role_permission",
  "allow_customer_referral",
  "view_customer",
  "edit_customer",
  "view_order",
  "change_order_priority",
  "undo_order_status",
  "download_order_list",
  "manage_reason",
  "manage_holiday",
  "manage_min_order_value",
  "validate_order",
  "download_order_monthly",
  "toggle_stock_finance",
  "view_product",
  "create_product",
  "edit_product_names",
  "create_product_bundle",
  "create_promotion",
  "edit_product_variants",
  "edit_variant_display_name",
  "edit_variant_pricing",
  "edit_variant_alerzoshop_status",
  "edit_product_categories",
  "edit_product_sub-categories",
  "edit_product_manufacturers",
  "edit_product_brands",
  "view_warehouse",
  "create_warehouse",
  "edit_state",
  "edit_city",
  "edit_landmark",
  "view_stock",
  "view_procurement",
  "create_procurement",
  "approve_procurement",
  "view_transfer",
  "create_transfer",
  "approve_transfer",
  "view_incident",
  "approve_incident",
  "create_incident",
  "assign_vehicle",
  "view_route",
  "create_route",
  "assign_route",
  "edit_route",
  "view_todo",
  "view_pos_manager",
  "assign_terminal",
  "download_transaction_history",
  "view_payment_tab",
  "validate_payment",
  "undo_payment_status",
  "view_seller",
  "create_seller",
  "edit_seller",
  "view_vendor",
  "create_vendor",
  "edit_vendor",
  "view_purchase_requisition",
  "create_purchase_requisition",
  "submit_purchase_requisition",
  "approve_purchase_requisition",
  "view_purchase_order",
  "approve_purchase_order",
  "audit_purchase_order",
  "pay_purchase_order",
  "notify_purchase_order",
  "view_transaction",
  "create_transaction",
  "modify_transaction",
  "prepare_transaction",
  "verify_transaction",
  "approve_transaction",
  "dispatch_transaction",
  "create_sale_order",
  "return_transaction",
  "approve_return_transaction",
  "cancel_transaction",
  "create_plan",
  "edit_plan",
  "delete_plan",
  "view_request",
  "view_requestListing",
  "create_request",
  "modify_request",
  "approve_request",
  "request_review",
  "decline_request",
  "request_inprogress",
  "request_completed",
  "view_admin_dashboard",
  "view_visitation_log",
  "view_crm_visitation_log",
  "view_pricing_visitation_log",
  "view_bde_visitation_log",
  "view_depot",
];

export const createDemoJwt = () => {
  const header = Buffer.from(JSON.stringify({ alg: "none", typ: "JWT" }))
    .toString("base64url");
  const payload = Buffer.from(
    JSON.stringify({
      sub: "user-1",
      userId: "user-1",
      name: "Demo Admin",
      permissions: demoPermissions,
      exp: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 30,
    }),
  ).toString("base64url");

  return `${header}.${payload}.demo-signature`;
};

export const warehouses = [
  {
    _id: "warehouse-1",
    id: "warehouse-1",
    warehouseId: "warehouse-1",
    warehouseName: "Ibadan Main Warehouse",
    name: "Ibadan Main Warehouse",
    prefix: "IBM",
    status: "Active",
    isActive: true,
    isDepot: false,
    address: "Alerzo Demo Road, Ibadan",
    lat: 7.3775,
    long: 3.947,
    City: {
      cityId: "city-1",
      cityName: "Ibadan",
      State: { stateId: "state-1", stateName: "Oyo" },
    },
    State: { stateId: "state-1", stateName: "Oyo" },
    Distributor: {
      distributorId: "distributor-1",
      distributorName: "Demo Distributor Ltd",
    },
  },
  {
    _id: "warehouse-2",
    id: "warehouse-2",
    warehouseId: "warehouse-2",
    warehouseName: "Lagos Demo Depot",
    name: "Lagos Demo Depot",
    prefix: "LDD",
    status: "Active",
    isActive: true,
    isDepot: true,
    address: "Demo Avenue, Ikeja, Lagos",
    lat: 6.6018,
    long: 3.3515,
    City: {
      cityId: "city-2",
      cityName: "Lagos",
      State: { stateId: "state-2", stateName: "Lagos" },
    },
    State: { stateId: "state-2", stateName: "Lagos" },
  },
];

const demoRole = {
  _id: "role-1",
  id: "role-1",
  roleId: "role-1",
  roleName: "Super Admin",
  country: "NG",
  permissions: demoPermissions,
  Permissions: demoPermissions.map((permission, index) => ({
    permissionId: `permission-${index + 1}`,
    permissionName: permission,
  })),
};

export const demoUser = {
  _id: "user-1",
  id: "user-1",
  userId: "user-1",
  firstName: "Demo",
  lastName: "Admin",
  fullName: "Demo Admin",
  name: "Demo Admin",
  userName: "demo.admin",
  email: "demo@example.com",
  phoneNumber: "+2348012345678",
  phoneNo: "+2348012345678",
  staffId: "ALZ001",
  status: "ACTIVE",
  isActive: true,
  isAlerzoUser: true,
  sellerId: "seller-1",
  warehouseId: "warehouse-1",
  imageUrl: UNSPLASH.avatar,
  allowedCountries: ["NG", "UG"],
  lastUserAccessTime: "2026-05-21T10:00:00.000Z",
  lastActiveIP: "127.0.0.1",
  lastUsedPlatform: "ADMIN_WEB",
  Roles: [demoRole],
  Warehouses: [],
  warehouse: warehouses[0],
  createdAt: "2026-05-21T10:00:00.000Z",
};

export const demoUsers = [
  demoUser,
  {
    ...demoUser,
    _id: "user-2",
    id: "user-2",
    userId: "user-2",
    fullName: "Alice Admin",
    name: "Alice Admin",
    userName: "ada.ops",
    email: "ada.ops@example.com",
    phoneNo: "+2348090001001",
    sellerId: "seller-1",
    Roles: [{ ...demoRole, roleId: "role-2", roleName: "Admin" }],
  },
  {
    ...demoUser,
    _id: "user-3",
    id: "user-3",
    userId: "user-3",
    fullName: "Demo Staff",
    name: "Demo Staff",
    userName: "chidi.wh",
    email: "chidi.wh@example.com",
    phoneNo: "+2348090001002",
    warehouseId: "warehouse-2",
    warehouse: warehouses[1],
    Roles: [{ ...demoRole, roleId: "role-3", roleName: "Inventory Officer" }],
  },
];

export const states = [
  {
    stateId: "state-1",
    id: "state-1",
    stateName: "Oyo",
    region: "South West",
    Cities: [{ cityId: "city-1", cityName: "Ibadan" }],
  },
  {
    stateId: "state-2",
    id: "state-2",
    stateName: "Lagos",
    region: "South West",
    Cities: [{ cityId: "city-2", cityName: "Lagos" }],
  },
];

export const products = [
  {
    _id: "product-1",
    id: "product-1",
    productId: "product-1",
    variantId: "variant-1",
    productName: "Golden Penny Noodles",
    variantName: "Golden Penny Noodles 70g",
    displayName: "Golden Penny Noodles 70g",
    name: "Golden Penny Noodles 70g",
    sku: "ALZ-NDL-70",
    price: 3200,
    sellingPrice: 3200,
    quantity: 240,
    stock: 240,
    categoryName: "Food",
    brandName: "Golden Penny",
    manufacturerName: "Flour Mills",
    imageUrl: UNSPLASH.noodles,
    isActive: true,
  },
  {
    _id: "product-2",
    id: "product-2",
    productId: "product-2",
    variantId: "variant-2",
    productName: "Demo Cooking Oil",
    variantName: "Demo Cooking Oil 5L",
    displayName: "Demo Cooking Oil 5L",
    name: "Demo Cooking Oil 5L",
    sku: "ALZ-OIL-5L",
    price: 8500,
    sellingPrice: 8500,
    quantity: 120,
    stock: 120,
    categoryName: "Groceries",
    brandName: "Alerzo Demo",
    manufacturerName: "Demo Foods",
    imageUrl: UNSPLASH.oil,
    isActive: true,
  },
];

export const customers = [
  {
    _id: "customer-1",
    id: "customer-1",
    customerId: "customer-1",
    businessName: "Mama T Demo Store",
    contactName: "Tina Davis",
    name: "Mama T Demo Store",
    email: "customer@example.com",
    phoneNumber: "+2348090001111",
    phoneNo: "+2348090001111",
    customerIdentifier: "CUST-001",
    legacyUniqueId: "LEG-001",
    status: "ACTIVE",
    city: "Ibadan",
    state: "Oyo",
    address: "12 Demo Market Road",
    walletBalance: 45000,
    creditLimit: 250000,
    isBlackListed: false,
    agentName: "Demo Admin",
    customerProfileImage: UNSPLASH.store,
    createdAt: "2026-01-15T10:00:00.000Z",
    Store: { storeId: "store-1", storeName: "Mama T Demo Store" },
    Stores: [
      {
        storeId: "store-1",
        typeOfStore: "retail",
        city: "Ibadan",
        landmark: "Dugbe Market",
        contactName: "Tina Davis",
        address: "12 Demo Market Road",
      },
    ],
  },
  {
    _id: "customer-2",
    id: "customer-2",
    customerId: "customer-2",
    businessName: "Lagos Retail Hub",
    contactName: "Bob Johnson",
    name: "Lagos Retail Hub",
    email: "retail@example.com",
    phoneNumber: "+2348090002222",
    phoneNo: "+2348090002222",
    customerIdentifier: "CUST-002",
    legacyUniqueId: "LEG-002",
    status: "ACTIVE",
    city: "Lagos",
    state: "Lagos",
    address: "45 Demo Trade Street",
    walletBalance: 90000,
    creditLimit: 400000,
    isBlackListed: false,
    agentName: "Alice Admin",
    customerProfileImage: UNSPLASH.store,
    createdAt: "2026-02-10T10:00:00.000Z",
    Stores: [
      {
        storeId: "store-2",
        typeOfStore: "wholesale",
        city: "Lagos",
        landmark: "Ikeja Market",
        contactName: "Bob Johnson",
        address: "45 Demo Trade Street",
      },
    ],
  },
  {
    _id: "customer-3",
    id: "customer-3",
    customerId: "customer-3",
    businessName: "University Kiosk",
    contactName: "Charlie Brown",
    name: "University Kiosk",
    email: "kiosk@example.com",
    phoneNumber: "+2348090003333",
    phoneNo: "+2348090003333",
    customerIdentifier: "CUST-003",
    legacyUniqueId: "LEG-003",
    status: "ACTIVE",
    city: "Ibadan",
    state: "Oyo",
    address: "8 Campus Road",
    walletBalance: 22000,
    creditLimit: 150000,
    isBlackListed: false,
    agentName: "Demo Staff",
    customerProfileImage: UNSPLASH.store,
    createdAt: "2026-03-05T10:00:00.000Z",
    Stores: [
      {
        storeId: "store-3",
        typeOfStore: "retail",
        city: "Ibadan",
        landmark: "UI Gate",
        contactName: "Charlie Brown",
        address: "8 Campus Road",
      },
    ],
  },
];

const demoOrderCustomer = {
  ...customers[0],
  customerIdentifier: "CUST-001",
  phoneNo: customers[0].phoneNumber,
  Stores: [
    {
      landmark: "Dugbe Market",
      contactName: customers[0].contactName,
      address: customers[0].address,
      lat: 7.387,
      long: 3.896,
    },
  ],
};

export const orders = [
  {
    _id: "order-1",
    id: "order-1",
    orderId: "order-1",
    orderNumber: "ALZ-ORD-1001",
    referenceId: "ALZ-ORD-1001",
    status: "processing",
    displayStatus: "processing",
    statusLabel: "Processing",
    totalAmount: 62800,
    orderTotal: 62800,
    sellerTotal: 62800,
    deliveryFee: 1200,
    platform: "ADMIN_WEB",
    priority: 0,
    isPrePaid: false,
    isStockFinanceable: false,
    possibleDuplicate: false,
    isSelfPickup: false,
    isPaid: true,
    preferredDeliveryDate: "2026-05-22T00:00:00.000Z",
    totalItemQuantity: 8,
    customerId: customers[0].customerId,
    warehouseId: warehouses[0].warehouseId,
    createdAt: "2026-05-20T09:30:00.000Z",
    updatedAt: "2026-05-20T09:30:00.000Z",
    customer: demoOrderCustomer,
    warehouse: warehouses[0],
    vehicles: [
      {
        vehicleId: "vehicle-1",
        vehicleNumber: "ABC123DE",
        vehicleType: "Van",
        status: "assigned",
      },
    ],
    items: products.map((product) => ({
      ...product,
      quantity: 4,
      amount: product.price * 4,
    })),
  },
  {
    _id: "order-2",
    id: "order-2",
    orderId: "order-2",
    orderNumber: "ALZ-ORD-1002",
    referenceId: "ALZ-ORD-1002",
    status: "delivered",
    displayStatus: "delivered",
    statusLabel: "Delivered",
    totalAmount: 45200,
    orderTotal: 45200,
    sellerTotal: 45200,
    deliveryFee: 1000,
    platform: "ALERZOSHOP_APP",
    priority: 1,
    isPrePaid: true,
    isStockFinanceable: true,
    possibleDuplicate: false,
    isSelfPickup: false,
    isPaid: true,
    preferredDeliveryDate: null,
    totalItemQuantity: 5,
    customerId: customers[1].customerId,
    warehouseId: warehouses[1].warehouseId,
    createdAt: "2026-05-19T14:15:00.000Z",
    updatedAt: "2026-05-19T18:45:00.000Z",
    customer: {
      ...customers[1],
      customerIdentifier: "CUST-002",
      phoneNo: customers[1].phoneNumber,
      Stores: [
        {
          landmark: "Ikeja Market",
          contactName: customers[1].contactName,
          address: customers[1].address,
          lat: 6.6018,
          long: 3.3515,
        },
      ],
    },
    warehouse: warehouses[1],
    vehicles: [],
    items: products.slice(0, 1).map((product) => ({
      ...product,
      quantity: 5,
      amount: product.price * 5,
    })),
  },
];

export const vehicles = [
  {
    _id: "vehicle-1",
    id: "vehicle-1",
    vehicleId: "vehicle-1",
    vehicleNumber: "ABC123DE",
    registration: "ABC123DE",
    model: "Toyota HiAce",
    vehicleType: "Van",
    type: "Van",
    status: "available",
    warehouse: warehouses[0],
    warehouseId: "warehouse-1",
  },
  {
    _id: "vehicle-2",
    id: "vehicle-2",
    vehicleId: "vehicle-2",
    vehicleNumber: "KJA456XY",
    registration: "KJA456XY",
    model: "Suzuki Mini Truck",
    vehicleType: "Truck",
    type: "Truck",
    status: "assigned",
    warehouse: warehouses[1],
    warehouseId: "warehouse-2",
  },
];

export const sellers = [
  {
    _id: "seller-1",
    id: "seller-1",
    sellerId: "seller-1",
    businessName: "Demo FMCG Seller",
    sellerName: "Demo FMCG Seller",
    name: "Demo FMCG Seller",
    sellerType: "primary",
    contactName: "Demo Contact",
    contactPhone: "+2348090003333",
    contactEmail: "seller@example.com",
    email: "seller@example.com",
    phoneNumber: "+2348090003333",
    registrationPrefix: "DFS",
    registrationNumber: "RC-SELLER-001",
    city: "Ibadan",
    state: "Oyo",
    status: "ACTIVE",
    logo: UNSPLASH.seller,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    _id: "seller-2",
    id: "seller-2",
    sellerId: "seller-2",
    businessName: "Lagos Wholesale Co",
    sellerName: "Lagos Wholesale Co",
    name: "Lagos Wholesale Co",
    sellerType: "secondary",
    contactName: "Wholesale Lead",
    contactPhone: "+2348090003334",
    contactEmail: "wholesale@example.com",
    registrationPrefix: "LWC",
    registrationNumber: "RC-SELLER-002",
    city: "Lagos",
    state: "Lagos",
    status: "ACTIVE",
    logo: UNSPLASH.seller,
    createdAt: "2026-02-01T00:00:00.000Z",
  },
];

export const vendors = [
  {
    _id: "vendor-1",
    id: "vendor-1",
    vendorId: "vendor-1",
    vendorName: "Demo Supplier Ltd",
    businessName: "Demo Supplier Ltd",
    referenceId: "VND-001",
    contactName: "Vendor Contact",
    email: "vendor@example.com",
    phoneNumber: "+2348090004444",
    vendorType: "primary",
    image: UNSPLASH.vendor,
    state: "Oyo",
    city: "Ibadan",
    address: "22 Supplier Avenue, Ibadan",
    isActive: true,
    status: "ACTIVE",
    creditLimit: 5000000,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    _id: "vendor-2",
    id: "vendor-2",
    vendorId: "vendor-2",
    vendorName: "Fresh Foods Wholesale",
    businessName: "Fresh Foods Wholesale",
    referenceId: "VND-002",
    contactName: "Fresh Foods Contact",
    email: "fresh@example.com",
    phoneNumber: "+2348090004445",
    vendorType: "secondary",
    image: UNSPLASH.vendor,
    state: "Lagos",
    city: "Lagos",
    address: "5 Industrial Estate, Lagos",
    isActive: true,
    status: "ACTIVE",
    creditLimit: 3000000,
    createdAt: "2026-02-15T00:00:00.000Z",
  },
];

export const variantProducts = products.map((product) => toVariantProduct(product));

export const catalogProducts = products.map((product) => ({
  _id: product._id,
  productName: product.productName,
  subCategory: product.categoryName === "Food" ? "Noodles" : "Cooking Oil",
  category: product.categoryName,
  brand: product.brandName,
  manufacturer: product.manufacturerName,
  isActive: product.isActive,
  vertical: "FMCG",
  variants: [
    {
      variantName: product.variantName,
      displayTitle: product.displayName,
    },
  ],
}));

export const bundleProducts = variantProducts;

export const pageInfo = (items: unknown[], page = 1, size = 50): PageInfo => ({
  totalItems: items.length,
  totalCount: items.length,
  currentPage: page,
  page,
  size,
  hasNextPage: false,
  hasPreviousPage: false,
});

export const paginated = (items: unknown[], page = 1, size = 50) => ({
  nodes: items,
  data: items,
  items,
  total: items.length,
  count: items.length,
  pageInfo: pageInfo(items, page, size),
});

export const genericLog = {
  _id: "log-1",
  id: "log-1",
  action: "Demo action",
  message: "Dummy backend event generated for portfolio walkthrough.",
  createdAt: "2026-05-21T10:00:00.000Z",
  Author: demoUser,
  author: demoUser,
};

export const categories = [
  { _id: "cat-1", categoryId: "cat-1", category_name: "Food", categoryName: "Food", name: "Food", categoryPrefix: "FD", isActive: true, vertical: "FMCG", verticalId: "vertical-1" },
  { _id: "cat-2", categoryId: "cat-2", category_name: "Beverages", categoryName: "Beverages", name: "Beverages", categoryPrefix: "BV", isActive: true, vertical: "FMCG", verticalId: "vertical-1" },
  { _id: "cat-3", categoryId: "cat-3", category_name: "Household", categoryName: "Household", name: "Household", categoryPrefix: "HH", isActive: true, vertical: "FMCG", verticalId: "vertical-1" },
];

export const subCategories = [
  { _id: "subcat-1", subCategoryId: "subcat-1", subCategoryName: "Noodles", name: "Noodles", categoryId: "cat-1", isActive: true },
  { _id: "subcat-2", subCategoryId: "subcat-2", subCategoryName: "Cooking Oil", name: "Cooking Oil", categoryId: "cat-1", isActive: true },
];

export const brands = [
  { _id: "brand-1", brandId: "brand-1", brandName: "Golden Penny", name: "Golden Penny", isActive: true },
  { _id: "brand-2", brandId: "brand-2", brandName: "Alerzo Demo", name: "Alerzo Demo", isActive: true },
];

export const manufacturers = [
  { _id: "mfr-1", manufacturerId: "mfr-1", manufacturerName: "Flour Mills Nigeria", name: "Flour Mills Nigeria", isActive: true },
  { _id: "mfr-2", manufacturerId: "mfr-2", manufacturerName: "Demo Foods Ltd", name: "Demo Foods Ltd", isActive: true },
];

export const verticals = [
  { _id: "vertical-1", verticalId: "vertical-1", verticalName: "FMCG", name: "FMCG", isActive: true },
  { _id: "vertical-2", verticalId: "vertical-2", verticalName: "Pharma", name: "Pharma", isActive: true },
];

export const landmarks = [
  {
    landmarkId: "landmark-1",
    _id: "landmark-1",
    landmarkName: "Dugbe Market",
    lat: 7.387,
    long: 3.896,
    isActive: true,
    Warehouse: warehouses[0],
    LGA: { lgaId: "lga-1", lgaName: "Ibadan North" },
  },
  {
    landmarkId: "landmark-2",
    _id: "landmark-2",
    landmarkName: "Ojoo Junction",
    lat: 7.432,
    long: 3.912,
    isActive: true,
    Warehouse: warehouses[0],
    LGA: { lgaId: "lga-1", lgaName: "Ibadan North" },
  },
];

export const lgas = [
  { lgaId: "lga-1", _id: "lga-1", lgaName: "Ibadan North", cityId: "city-1", stateId: "state-1", isActive: true },
  { lgaId: "lga-2", _id: "lga-2", lgaName: "Ikeja", cityId: "city-2", stateId: "state-2", isActive: true },
];

export const demoTransfer = {
  _id: "transfer-1",
  id: "transfer-1",
  referenceId: "TRF-001",
  status: "pending",
  fromWarehouseId: "warehouse-1",
  toWarehouseId: "warehouse-2",
  fromWarehouseDetails: warehouses[0],
  toWarehouseDetails: warehouses[1],
  driverDetails: demoUser,
  stockControllerDetails: demoUser,
  vehicleNumber: "ABC123DE",
  createdAt: "2026-05-20T09:00:00.000Z",
  stockProducts: products.map((p) => ({ ...p, value: 10 })),
  stock: products.map((p) => ({ productId: p._id, value: 10 })),
};

export const demoProcurement = {
  _id: "procurement-1",
  id: "procurement-1",
  referenceId: "PCM-001",
  status: "pending",
  warehouseId: "warehouse-1",
  driverName: "Demo Driver",
  vehicleNumber: "ABC123DE",
  distributor: "Demo Distributor",
  manufacturer: "Flour Mills Nigeria",
  comment: "Demo procurement",
  invoiceNumber: "INV-001",
  waybillNumber: "WB-001",
  createdAt: "2026-05-20T09:00:00.000Z",
  stockProducts: products.map((p) => ({ ...p, value: 50 })),
  stock: products.map((p) => ({ productId: p._id, value: 50 })),
  stockControllerDetails: demoUser,
};

export const demoIncident = {
  _id: "incident-1",
  id: "incident-1",
  referenceId: "INC-001",
  status: "pending",
  warehouseId: "warehouse-1",
  incidentType: "damage",
  reason: "Demo incident reason",
  comment: "Demo incident comment",
  userRole: "Inventory Officer",
  userDetails: demoUser,
  warehouseDetails: warehouses[0],
  createdAt: "2026-05-20T09:00:00.000Z",
  stockProducts: products.map((p) => ({ ...p, value: 5 })),
  stock: products.map((p) => ({ productId: p._id, value: 5 })),
};

export const demoPurchaseRequisition = {
  _id: "pr-1",
  id: "pr-1",
  referenceId: "PR-001",
  status: "pending",
  warehouseId: "warehouse-1",
  warehouseName: "Ibadan Main Warehouse",
  reason: "Demo restock",
  sellerId: "seller-1",
  sellerDetails: sellers[0],
  requestedBy: "Demo Admin",
  createdAt: "2026-05-20T09:00:00.000Z",
  products: products.map((p) => ({ productId: p._id, quantity: 100, price: p.price })),
};

export const demoPurchaseOrder = {
  _id: "po-1",
  id: "po-1",
  referenceId: "PO-001",
  purchaseRequisitionReferenceId: "PR-001",
  status: "pending",
  totalAmount: 320000,
  estimatedArrival: "2026-05-25T00:00:00.000Z",
  reason: "Demo purchase order",
  leadTime: 3,
  paymentDetails: { creditBalance: 500000 },
  createdAt: "2026-05-20T09:00:00.000Z",
};

export const demoInStoreTransaction = {
  _id: "ist-1",
  id: "ist-1",
  referenceId: "IST-001",
  status: "transaction_pending",
  warehouseId: "warehouse-1",
  warehouseDetails: warehouses[0],
  createdAt: "2026-05-20T09:00:00.000Z",
  products: products.map((p) => ({ ...p, quantity: 10 })),
};

export const demoDeliveryPlan = {
  _id: "plan-1",
  id: "plan-1",
  planId: "plan-1",
  referenceId: "PLN-001",
  status: "unassigned",
  warehouseId: "warehouse-1",
  warehouse: warehouses[0],
  vehicle: vehicles[0],
  driver: demoUser,
  orders,
  createdAt: "2026-05-20T09:00:00.000Z",
};

export const demoVehicleRequest = {
  _id: "vr-1",
  id: "vr-1",
  referenceId: "VR-001",
  status: "pending",
  warehouseId: "warehouse-1",
  requestedBy: demoUser,
  createdAt: "2026-05-20T09:00:00.000Z",
};

export const demoTerminal = {
  terminalId: "terminal-1",
  _id: "terminal-1",
  serialNumber: "SN-DEMO-001",
  posTerminalId: "POS-001",
  referenceId: "TRM-001",
  provider: "Demo POS Provider",
  posVariant: "standard",
  status: "unassigned",
  userId: null,
  isActive: true,
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
};

export const demoDeliveryFee = {
  _id: "fee-1",
  id: "fee-1",
  referenceId: "DF-001",
  deliveryFeeName: "Standard Delivery Fee",
  amount: 500,
  feeType: "flat",
  status: "ACTIVE",
  platform: "ADMIN_WEB",
  warehouseId: "warehouse-1",
  warehouse: warehouses[0],
  verticalId: "vertical-1",
  verticalName: "FMCG",
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
  rangeConstraints: [],
};

export const demoProcessingFee = {
  _id: "pfee-1",
  id: "pfee-1",
  referenceId: "PF-001",
  paymentProvider: "PAYSTACK",
  paymentMethod: "CARD",
  chargeType: "percentage",
  charge: 150,
  minChargePercent: 1,
  paymentMode: "online",
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
  constraints: { maxAmount: 2000, minAmount: 100 },
};

export const demoDistributor = {
  _id: "distributor-1",
  id: "distributor-1",
  distributorId: "distributor-1",
  distributorName: "Demo Distributor Ltd",
  distributorType: "primary",
  address: "Demo Distributor Address",
  contactName: "Distributor Contact",
  email: "distributor@example.com",
  phoneNumber: "+2348090005555",
  bvn: "12345678901",
  cacNumber: "RC-DEMO-001",
  logo: null,
  verticalId: "vertical-1",
  vertical: "FMCG",
  isActive: true,
  paymentType: "credit",
  categoryIds: ["cat-1"],
  categories: ["Food"],
  registrationPrefix: "DD",
  creditTerm: 30,
  Warehouses: [warehouses[0]],
  cityId: "city-1",
  City: { cityId: "city-1", cityName: "Ibadan", State: { stateId: "state-1", stateName: "Oyo" } },
};

export const demoInventoryItem = {
  _id: "inv-1",
  productId: "product-1",
  stockValue: 240,
  availableStock: 200,
  status: "in_stock",
  product: {
    ...products[0],
    displayTitle: "Golden Penny Noodles 70g",
    product_SKU: "ALZ-NDL-70",
    images: [{ imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246" }],
  },
  sellerDetails: [{ _id: "seller-1", sellerName: "Demo FMCG Seller" }],
  verticalName: "FMCG",
};

export const demoRoute = {
  _id: "route-1",
  id: "route-1",
  routeId: "route-1",
  referenceId: "RT-001",
  routeName: "Ibadan Demo Route",
  status: "Active",
  driverName: demoUser.fullName,
  vehicleNumber: vehicles[0].vehicleNumber,
  vehicleType: vehicles[0].vehicleType,
  ordersCount: orders.length,
  ordercount: orders.length,
  eta: "2h 15m",
  actualtime: "2h 05m",
  routeDate: "2026-05-21T08:00:00.000Z",
  dispatchTime: "2026-05-21T08:15:00.000Z",
  completedTime: "2026-05-21T10:20:00.000Z",
  workingTime: "2h 15m",
  distance: "18.4 km",
  warehouse: warehouses[0],
  Warehouse: warehouses[0],
  vehicle: vehicles[0],
  Vehicle: vehicles[0],
  driver: demoUser,
  Driver: demoUser,
  salesRepresentative: demoUser,
  salesDriver: demoUser,
  orders,
  lat: 7.3775,
  long: 3.947,
};

export const demoOrderPerformance = {
  orderReceived: 128,
  orderCancelled: 6,
  orderReturned: 4,
  totalTrips: 42,
};

export const demoSalesBySegment = [
  {
    segment: "Active Customer",
    totalSales: 2500000,
    totalOrders: 85,
    totalCustomers: 40,
    percentageOfTotalSales: 45,
  },
  {
    segment: "Inactive Customer",
    totalSales: 1200000,
    totalOrders: 32,
    totalCustomers: 18,
    percentageOfTotalSales: 22,
  },
  {
    segment: "Dormant Customer",
    totalSales: 900000,
    totalOrders: 21,
    totalCustomers: 12,
    percentageOfTotalSales: 16,
  },
  {
    segment: "Churned Customer",
    totalSales: 950000,
    totalOrders: 19,
    totalCustomers: 9,
    percentageOfTotalSales: 17,
  },
];

export const demoInventoryMetrics = {
  inventoryValuation: 12500000,
  inventoryCount: 1840,
};

export const demoStockByCategory = warehouses.map((warehouse) => ({
  warehouseName: warehouse.warehouseName,
  categories: categories.slice(0, 3).map((category, index) => ({
    categoryName: category.categoryName,
    stockValuation: 1800000 + index * 350000,
    stockCount: 240 + index * 80,
  })),
}));

export const demoTotalSales = warehouses.map((warehouse, index) => ({
  warehouseId: warehouse.warehouseId,
  warehouseName: warehouse.warehouseName,
  totalSales: 1500000 + index * 750000,
}));

export const demoTopSellingProducts = products.map((product, index) => ({
  productId: product.productId,
  productSKU: product.sku,
  displayTitle: product.displayName,
  totalSales: product.price * (40 - index * 10),
  quantitySold: 40 - index * 10,
}));

export const demoTopProductsByCancellation = products.map((product, index) => ({
  productId: product.productId,
  productSKU: product.sku,
  displayTitle: product.displayName,
  numberOfTimesCancelled: 2 + index,
  quantityCancelled: 5 + index,
  quantitySold: 40 - index * 10,
  imageUrl: product.imageUrl,
  cancelledValuation: product.price * (5 + index),
}));

export const demoSalesTrend = [
  {
    date: "2026-05-19",
    products: products.map((product) => ({
      product: product.displayName,
      totalSales: product.price * 20,
    })),
  },
  {
    date: "2026-05-20",
    products: products.map((product) => ({
      product: product.displayName,
      totalSales: product.price * 28,
    })),
  },
  {
    date: "2026-05-21",
    products: products.map((product) => ({
      product: product.displayName,
      totalSales: product.price * 35,
    })),
  },
];

export const demoStockForecastNodes = products.map((product, index) => ({
  productId: product.productId,
  warehouseId: warehouses[0].warehouseId,
  product: {
    product_SKU: product.sku,
    displayTitle: product.displayName,
  },
  date: "2026-05-21",
  fcMonthlyAvg: 120 + index * 15,
  fcDemand: 90 + index * 10,
  leadTime: 3,
  quantityToOrder: 50 + index * 5,
  quantity: 240 - index * 20,
  stockValue: product.price * (240 - index * 20),
  Fill_Rate: 0.92,
  orderBy: "Demo Admin",
  warehouseDetails: warehouses[0],
}));

export const demoCoupon = {
  _id: "coupon-1",
  id: "coupon-1",
  couponName: "Demo Welcome Coupon",
  couponCode: "DEMO10",
  couponDescription: "10% off demo orders",
  platformApplicable: "ADMIN_WEB",
  stateId: "state-1",
  cityId: "city-1",
  warehouseId: "warehouse-1",
  discountType: "percentage",
  discount: 10,
  customerSegement: "Active Customer",
  usesPerCoupon: 100,
  usesPerCustomer: 1,
  cartValue: 5000,
  startDate: "2026-01-01",
  endDate: "2026-12-31",
  termsAndCondition: "Demo terms and conditions",
  status: "ACTIVE",
  createdAt: "2026-01-01T00:00:00.000Z",
};

const bannerImageVersions = [
  { language: "en", imageUrl: UNSPLASH.banner },
  { language: "yo", imageUrl: UNSPLASH.store },
];

export const demoBanner = {
  _id: "banner-1",
  id: "banner-1",
  bannerName: "Summer Promo Banner",
  title: "Summer Promo Banner",
  image: UNSPLASH.banner,
  imageUrl: UNSPLASH.banner,
  isActive: true,
  status: "ACTIVE",
  redirectTo: "/products",
  redirectType: "internal",
  redirectValue: "product-1",
  position: "home_top",
  category: "Food",
  state: "Oyo",
  city: "Ibadan",
  warehouse: "Ibadan Main Warehouse",
  customerSegment: "Active Customer",
  platform: "ADMIN_WEB",
  startDate: "2026-01-01T00:00:00.000Z",
  endDate: "2026-12-31T23:59:59.000Z",
  duration: 30,
  priority: 1,
  params: [{ name: "campaign", value: "demo-summer" }],
  desktopVersion: bannerImageVersions,
  mobileVersion: bannerImageVersions,
  createdAt: "2026-01-01T00:00:00.000Z",
};

export const demoBundle = {
  _id: "bundle-1",
  id: "bundle-1",
  bundleName: "Demo Bundle Pack",
  bundleType: "STANDARD",
  description: "Demo bundle for portfolio walkthrough",
  bundleCities: [{ bundleCityId: "city-1", minimumQuantity: 1, warehouseId: "warehouse-1" }],
  bundleProducts,
  promotedProducts: bundleProducts.slice(0, 1),
  desktopVersion: bannerImageVersions,
  mobileVersion: bannerImageVersions,
  sector: { sectorId: "sector-1", sectorName: "Demo Sector" },
};

export const demoPromotion = {
  _id: "promo-1",
  id: "promo-1",
  promotionName: "Demo Promotion",
  promotionPlatform: "ADMIN_WEB",
  discountType: "percentage",
  discount: 15,
  brands: ["Golden Penny"],
  categories: ["Food"],
  cityId: "city-1",
  city: "Ibadan",
  state: "Oyo",
  stateId: "state-1",
  warehouseId: "warehouse-1",
  warehouse: "Ibadan Main Warehouse",
  status: "ACTIVE",
  startDate: "2026-01-01",
  endDate: "2026-12-31",
  vertical: "FMCG",
  verticalId: "vertical-1",
  customerSegments: [],
};

export const demoTodo = {
  _id: "todo-1",
  id: "todo-1",
  todoUrl: "/dashboard/orders/order-1",
  user_id: "user-1",
  todoType: "Order",
  action: "validate_order",
  nextAction: "dispatch_order",
  referenceId: "ALZ-ORD-1001",
  status: "pending",
  updatedAt: "2026-05-21T10:00:00.000Z",
  createdAt: "2026-05-21T10:00:00.000Z",
  object_id: "order-1",
  additionalRemarks: "Dugbe Market",
  warehouseId: "warehouse-1",
};

export const demoVisitation = {
  visitationId: "visit-1",
  _id: "visit-1",
  userId: "user-1",
  user: demoUser,
  customerId: "customer-1",
  Customer: customers[0],
  referenceId: "VIS-001",
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
};

export const demoUom = {
  _id: "uom-1",
  uomId: "uom-1",
  uomName: "Carton",
  uomSapId: "CTN",
  isActive: true,
};

export const demoBackOrderItem = {
  _id: "bo-1",
  id: "bo-1",
  referenceId: "BO-001",
  status: "pending",
  customerId: "customer-1",
  customer: customers[0],
  warehouseId: "warehouse-1",
  warehouse: warehouses[0],
  createdAt: "2026-05-20T09:00:00.000Z",
  items: products.map((p) => ({ ...p, quantity: 5 })),
};

