

const UNSPLASH = {
  avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
  store: "https://images.unsplash.com/photo-1556745757-8d76bdb6984b?w=600",
  noodles: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600",
  oil: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600",
  warehouse: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600",
  banner: "https://images.unsplash.com/photo-1556742049-0cfed4f06a45?w=1200",
  seller: "https://images.unsplash.com/photo-1560179707-fc0cdb330363?w=200",
  vendor: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=200",
};

export const toVariantProduct = (product: Record<string, unknown>) => ({
  ...product,
  displayTitle: product.displayName || product.variantName,
  product_SKU: product.sku,
  images: { imageUrl: product.imageUrl },
  pricing: {
    wholesalePrice: Math.round(Number(product.price) * 0.9),
    retailPrice: product.price,
    marketPrice: Math.round(Number(product.price) * 1.1),
  },
  maxPurchasePrice: product.price,
});

export const demoPermissions = [
  "access_admin",
  "access_sellers_portal",
  "view_users",
  "create_users",
  "change_password",
  "view_role_permission",
  "allow_customer_referral",
  "view_customer",
  "edit_customer",
  "view_order",
  "change_order_priority",
  "undo_order_status",
  "download_order_list",
  "manage_reason",
  "manage_holiday",
  "manage_min_order_value",
  "validate_order",
  "download_order_monthly",
  "toggle_stock_finance",
  "view_product",
  "create_product",
  "edit_product_names",
  "create_product_bundle",
  "create_promotion",
  "edit_product_variants",
  "edit_variant_display_name",
  "edit_variant_pricing",
  "edit_variant_alerzoshop_status",
  "edit_product_categories",
  "edit_product_sub-categories",
  "edit_product_manufacturers",
  "edit_product_brands",
  "view_warehouse",
  "create_warehouse",
  "edit_state",
  "edit_city",
  "edit_landmark",
  "view_stock",
  "view_procurement",
  "create_procurement",
  "approve_procurement",
  "view_transfer",
  "create_transfer",
  "approve_transfer",
  "view_incident",
  "approve_incident",
  "create_incident",
  "assign_vehicle",
  "view_route",
  "create_route",
  "assign_route",
  "edit_route",
  "view_todo",
  "view_pos_manager",
  "assign_terminal",
  "download_transaction_history",
  "view_payment_tab",
  "validate_payment",
  "undo_payment_status",
  "view_seller",
  "create_seller",
  "edit_seller",
  "view_vendor",
  "create_vendor",
  "edit_vendor",
  "view_purchase_requisition",
  "create_purchase_requisition",
  "submit_purchase_requisition",
  "approve_purchase_requisition",
  "view_purchase_order",
  "approve_purchase_order",
  "audit_purchase_order",
  "pay_purchase_order",
  "notify_purchase_order",
  "view_transaction",
  "create_transaction",
  "modify_transaction",
  "prepare_transaction",
  "verify_transaction",
  "approve_transaction",
  "dispatch_transaction",
  "create_sale_order",
  "return_transaction",
  "approve_return_transaction",
  "cancel_transaction",
  "create_plan",
  "edit_plan",
  "delete_plan",
  "view_request",
  "view_requestListing",
  "create_request",
  "modify_request",
  "approve_request",
  "request_review",
  "decline_request",
  "request_inprogress",
  "request_completed",
  "view_admin_dashboard",
  "view_visitation_log",
  "view_crm_visitation_log",
  "view_pricing_visitation_log",
  "view_bde_visitation_log",
  "view_depot",
];

export const createDemoJwt = () => {
  const header = Buffer.from(JSON.stringify({ alg: "none", typ: "JWT" }))
    .toString("base64url");
  const payload = Buffer.from(
    JSON.stringify({
      sub: "user-1",
      userId: "user-1",
      name: "Demo Admin",
      permissions: demoPermissions,
      exp: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 30,
    }),
  ).toString("base64url");

  return `${header}.${payload}.demo-signature`;
};

export const warehouses = [
  {
    _id: "warehouse-1",
    id: "warehouse-1",
    warehouseId: "warehouse-1",
    warehouseName: "Ibadan Main Warehouse",
    name: "Ibadan Main Warehouse",
    prefix: "IBM",
    status: "Active",
    isActive: true,
    isDepot: false,
    address: "Alerzo Demo Road, Ibadan",
    lat: 7.3775,
    long: 3.947,
    City: {
      cityId: "city-1",
      cityName: "Ibadan",
      State: { stateId: "state-1", stateName: "Oyo" },
    },
    State: { stateId: "state-1", stateName: "Oyo" },
    Distributor: {
      distributorId: "distributor-1",
      distributorName: "Demo Distributor Ltd",
    },
  },
  {
    _id: "warehouse-2",
    id: "warehouse-2",
    warehouseId: "warehouse-2",
    warehouseName: "Lagos Demo Depot",
    name: "Lagos Demo Depot",
    prefix: "LDD",
    status: "Active",
    isActive: true,
    isDepot: true,
    address: "Demo Avenue, Ikeja, Lagos",
    lat: 6.6018,
    long: 3.3515,
    City: {
      cityId: "city-2",
      cityName: "Lagos",
      State: { stateId: "state-2", stateName: "Lagos" },
    },
    State: { stateId: "state-2", stateName: "Lagos" },
  },
];

const demoRole = {
  _id: "role-1",
  id: "role-1",
  roleId: "role-1",
  roleName: "Super Admin",
  country: "NG",
  permissions: demoPermissions,
  Permissions: demoPermissions.map((permission, index) => ({
    permissionId: `permission-${index + 1}`,
    permissionName: permission,
  })),
};

export const demoUser = {
  _id: "user-1",
  id: "user-1",
  userId: "user-1",
  firstName: "Demo",
  lastName: "Admin",
  fullName: "Demo Admin",
  name: "Demo Admin",
  userName: "demo.admin",
  email: "demo@demo.com",
  phoneNumber: "+2348012345678",
  phoneNo: "+2348012345678",
  staffId: "ALZ001",
  status: "ACTIVE",
  isActive: true,
  isAlerzoUser: true,
  sellerId: "seller-1",
  warehouseId: "warehouse-1",
  imageUrl: UNSPLASH.avatar,
  allowedCountries: ["NG", "UG"],
  lastUserAccessTime: "2026-05-21T10:00:00.000Z",
  lastActiveIP: "127.0.0.1",
  lastUsedPlatform: "ADMIN_WEB",
  Roles: [demoRole],
  Warehouses: [],
  warehouse: warehouses[0],
  createdAt: "2026-05-21T10:00:00.000Z",
};

export const demoUsers = [
  demoUser,
  {
    ...demoUser,
    _id: "user-2",
    id: "user-2",
    userId: "user-2",
    fullName: "Ada Operations",
    name: "Ada Operations",
    userName: "ada.ops",
    email: "ada.ops@demo.com",
    phoneNo: "+2348090001001",
    sellerId: "seller-1",
    Roles: [{ ...demoRole, roleId: "role-2", roleName: "Admin" }],
  },
  {
    ...demoUser,
    _id: "user-3",
    id: "user-3",
    userId: "user-3",
    fullName: "Chidi Warehouse",
    name: "Chidi Warehouse",
    userName: "chidi.wh",
    email: "chidi.wh@demo.com",
    phoneNo: "+2348090001002",
    warehouseId: "warehouse-2",
    warehouse: warehouses[1],
    Roles: [{ ...demoRole, roleId: "role-3", roleName: "Inventory Officer" }],
  },
];

export const states = [
  {
    stateId: "state-1",
    id: "state-1",
    stateName: "Oyo",
    region: "South West",
    Cities: [{ cityId: "city-1", cityName: "Ibadan" }],
  },
  {
    stateId: "state-2",
    id: "state-2",
    stateName: "Lagos",
    region: "South West",
    Cities: [{ cityId: "city-2", cityName: "Lagos" }],
  },
];

export const products = [
  {
    _id: "product-1",
    id: "product-1",
    productId: "product-1",
    variantId: "variant-1",
    productName: "Golden Penny Noodles",
    variantName: "Golden Penny Noodles 70g",
    displayName: "Golden Penny Noodles 70g",
    name: "Golden Penny Noodles 70g",
    sku: "ALZ-NDL-70",
    price: 3200,
    sellingPrice: 3200,
    quantity: 240,
    stock: 240,
    categoryName: "Food",
    brandName: "Golden Penny",
    manufacturerName: "Flour Mills",
    imageUrl: UNSPLASH.noodles,
    isActive: true,
  },
  {
    _id: "product-2",
    id: "product-2",
    productId: "product-2",
    variantId: "variant-2",
    productName: "Demo Cooking Oil",
    variantName: "Demo Cooking Oil 5L",
    displayName: "Demo Cooking Oil 5L",
    name: "Demo Cooking Oil 5L",
    sku: "ALZ-OIL-5L",
    price: 8500,
    sellingPrice: 8500,
    quantity: 120,
    stock: 120,
    categoryName: "Groceries",
    brandName: "Alerzo Demo",
    manufacturerName: "Demo Foods",
    imageUrl: UNSPLASH.oil,
    isActive: true,
  },
];

export const customers = [
  {
    _id: "customer-1",
    id: "customer-1",
    customerId: "customer-1",
    businessName: "Mama T Demo Store",
    contactName: "Titi Ade",
    name: "Mama T Demo Store",
    email: "customer@example.com",
    phoneNumber: "+2348090001111",
    phoneNo: "+2348090001111",
    customerIdentifier: "CUST-001",
    legacyUniqueId: "LEG-001",
    status: "ACTIVE",
    city: "Ibadan",
    state: "Oyo",
    address: "12 Demo Market Road",
    walletBalance: 45000,
    creditLimit: 250000,
    isBlackListed: false,
    agentName: "Demo Admin",
    customerProfileImage: UNSPLASH.store,
    createdAt: "2026-01-15T10:00:00.000Z",
    Store: { storeId: "store-1", storeName: "Mama T Demo Store" },
    Stores: [
      {
        storeId: "store-1",
        typeOfStore: "retail",
        city: "Ibadan",
        landmark: "Dugbe Market",
        contactName: "Titi Ade",
        address: "12 Demo Market Road",
      },
    ],
  },
  {
    _id: "customer-2",
    id: "customer-2",
    customerId: "customer-2",
    businessName: "Lagos Retail Hub",
    contactName: "Bola James",
    name: "Lagos Retail Hub",
    email: "retail@example.com",
    phoneNumber: "+2348090002222",
    phoneNo: "+2348090002222",
    customerIdentifier: "CUST-002",
    legacyUniqueId: "LEG-002",
    status: "ACTIVE",
    city: "Lagos",
    state: "Lagos",
    address: "45 Demo Trade Street",
    walletBalance: 90000,
    creditLimit: 400000,
    isBlackListed: false,
    agentName: "Ada Operations",
    customerProfileImage: UNSPLASH.store,
    createdAt: "2026-02-10T10:00:00.000Z",
    Stores: [
      {
        storeId: "store-2",
        typeOfStore: "wholesale",
        city: "Lagos",
        landmark: "Ikeja Market",
        contactName: "Bola James",
        address: "45 Demo Trade Street",
      },
    ],
  },
  {
    _id: "customer-3",
    id: "customer-3",
    customerId: "customer-3",
    businessName: "University Kiosk",
    contactName: "Emeka Okafor",
    name: "University Kiosk",
    email: "kiosk@example.com",
    phoneNumber: "+2348090003333",
    phoneNo: "+2348090003333",
    customerIdentifier: "CUST-003",
    legacyUniqueId: "LEG-003",
    status: "ACTIVE",
    city: "Ibadan",
    state: "Oyo",
    address: "8 Campus Road",
    walletBalance: 22000,
    creditLimit: 150000,
    isBlackListed: false,
    agentName: "Chidi Warehouse",
    customerProfileImage: UNSPLASH.store,
    createdAt: "2026-03-05T10:00:00.000Z",
    Stores: [
      {
        storeId: "store-3",
        typeOfStore: "retail",
        city: "Ibadan",
        landmark: "UI Gate",
        contactName: "Emeka Okafor",
        address: "8 Campus Road",
      },
    ],
  },
];

const demoOrderCustomer = {
  ...customers[0],
  customerIdentifier: "CUST-001",
  phoneNo: customers[0].phoneNumber,
  Stores: [
    {
      landmark: "Dugbe Market",
      contactName: customers[0].contactName,
      address: customers[0].address,
      lat: 7.387,
      long: 3.896,
    },
  ],
};

export const orders = [
  {
    _id: "order-1",
    id: "order-1",
    orderId: "order-1",
    orderNumber: "ALZ-ORD-1001",
    referenceId: "ALZ-ORD-1001",
    status: "processing",
    displayStatus: "processing",
    statusLabel: "Processing",
    totalAmount: 62800,
    orderTotal: 62800,
    sellerTotal: 62800,
    deliveryFee: 1200,
    platform: "ADMIN_WEB",
    priority: 0,
    isPrePaid: false,
    isStockFinanceable: false,
    possibleDuplicate: false,
    isSelfPickup: false,
    isPaid: true,
    preferredDeliveryDate: "2026-05-22T00:00:00.000Z",
    totalItemQuantity: 8,
    customerId: customers[0].customerId,
    warehouseId: warehouses[0].warehouseId,
    createdAt: "2026-05-20T09:30:00.000Z",
    updatedAt: "2026-05-20T09:30:00.000Z",
    customer: demoOrderCustomer,
    warehouse: warehouses[0],
    vehicles: [
      {
        vehicleId: "vehicle-1",
        vehicleNumber: "ABC123DE",
        vehicleType: "Van",
        status: "assigned",
      },
    ],
    items: products.map((product) => ({
      ...product,
      quantity: 4,
      amount: product.price * 4,
    })),
  },
  {
    _id: "order-2",
    id: "order-2",
    orderId: "order-2",
    orderNumber: "ALZ-ORD-1002",
    referenceId: "ALZ-ORD-1002",
    status: "delivered",
    displayStatus: "delivered",
    statusLabel: "Delivered",
    totalAmount: 45200,
    orderTotal: 45200,
    sellerTotal: 45200,
    deliveryFee: 1000,
    platform: "ALERZOSHOP_APP",
    priority: 1,
    isPrePaid: true,
    isStockFinanceable: true,
    possibleDuplicate: false,
    isSelfPickup: false,
    isPaid: true,
    preferredDeliveryDate: null,
    totalItemQuantity: 5,
    customerId: customers[1].customerId,
    warehouseId: warehouses[1].warehouseId,
    createdAt: "2026-05-19T14:15:00.000Z",
    updatedAt: "2026-05-19T18:45:00.000Z",
    customer: {
      ...customers[1],
      customerIdentifier: "CUST-002",
      phoneNo: customers[1].phoneNumber,
      Stores: [
        {
          landmark: "Ikeja Market",
          contactName: customers[1].contactName,
          address: customers[1].address,
          lat: 6.6018,
          long: 3.3515,
        },
      ],
    },
    warehouse: warehouses[1],
    vehicles: [],
    items: products.slice(0, 1).map((product) => ({
      ...product,
      quantity: 5,
      amount: product.price * 5,
    })),
  },
];

export const vehicles = [
  {
    _id: "vehicle-1",
    id: "vehicle-1",
    vehicleId: "vehicle-1",
    vehicleNumber: "ABC123DE",
    registration: "ABC123DE",
    model: "Toyota HiAce",
    vehicleType: "Van",
    type: "Van",
    status: "available",
    warehouse: warehouses[0],
    warehouseId: "warehouse-1",
  },
  {
    _id: "vehicle-2",
    id: "vehicle-2",
    vehicleId: "vehicle-2",
    vehicleNumber: "KJA456XY",
    registration: "KJA456XY",
    model: "Suzuki Mini Truck",
    vehicleType: "Truck",
    type: "Truck",
    status: "assigned",
    warehouse: warehouses[1],
    warehouseId: "warehouse-2",
  },
];

export const sellers = [
  {
    _id: "seller-1",
    id: "seller-1",
    sellerId: "seller-1",
    businessName: "Demo FMCG Seller",
    sellerName: "Demo FMCG Seller",
    name: "Demo FMCG Seller",
    sellerType: "primary",
    contactName: "Demo Contact",
    contactPhone: "+2348090003333",
    contactEmail: "seller@example.com",
    email: "seller@example.com",
    phoneNumber: "+2348090003333",
    registrationPrefix: "DFS",
    registrationNumber: "RC-SELLER-001",
    city: "Ibadan",
    state: "Oyo",
    status: "ACTIVE",
    logo: UNSPLASH.seller,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    _id: "seller-2",
    id: "seller-2",
    sellerId: "seller-2",
    businessName: "Lagos Wholesale Co",
    sellerName: "Lagos Wholesale Co",
    name: "Lagos Wholesale Co",
    sellerType: "secondary",
    contactName: "Wholesale Lead",
    contactPhone: "+2348090003334",
    contactEmail: "wholesale@example.com",
    registrationPrefix: "LWC",
    registrationNumber: "RC-SELLER-002",
    city: "Lagos",
    state: "Lagos",
    status: "ACTIVE",
    logo: UNSPLASH.seller,
    createdAt: "2026-02-01T00:00:00.000Z",
  },
];

export const vendors = [
  {
    _id: "vendor-1",
    id: "vendor-1",
    vendorId: "vendor-1",
    vendorName: "Demo Supplier Ltd",
    businessName: "Demo Supplier Ltd",
    referenceId: "VND-001",
    contactName: "Vendor Contact",
    email: "vendor@example.com",
    phoneNumber: "+2348090004444",
    vendorType: "primary",
    image: UNSPLASH.vendor,
    state: "Oyo",
    city: "Ibadan",
    address: "22 Supplier Avenue, Ibadan",
    isActive: true,
    status: "ACTIVE",
    creditLimit: 5000000,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    _id: "vendor-2",
    id: "vendor-2",
    vendorId: "vendor-2",
    vendorName: "Fresh Foods Wholesale",
    businessName: "Fresh Foods Wholesale",
    referenceId: "VND-002",
    contactName: "Fresh Foods Contact",
    email: "fresh@example.com",
    phoneNumber: "+2348090004445",
    vendorType: "secondary",
    image: UNSPLASH.vendor,
    state: "Lagos",
    city: "Lagos",
    address: "5 Industrial Estate, Lagos",
    isActive: true,
    status: "ACTIVE",
    creditLimit: 3000000,
    createdAt: "2026-02-15T00:00:00.000Z",
  },
];

export const variantProducts = products.map((product) => toVariantProduct(product));

export const catalogProducts = products.map((product) => ({
  _id: product._id,
  productName: product.productName,
  subCategory: product.categoryName === "Food" ? "Noodles" : "Cooking Oil",
  category: product.categoryName,
  brand: product.brandName,
  manufacturer: product.manufacturerName,
  isActive: product.isActive,
  vertical: "FMCG",
  variants: [
    {
      variantName: product.variantName,
      displayTitle: product.displayName,
    },
  ],
}));

export const bundleProducts = variantProducts;

export const pageInfo = (items: unknown[], page = 1, size = 50) => ({
  totalItems: items.length,
  totalCount: items.length,
  currentPage: page,
  page,
  size,
  hasNextPage: false,
  hasPreviousPage: false,
});

export const paginated = (items: unknown[], page = 1, size = 50) => ({
  nodes: items,
  data: items,
  items,
  total: items.length,
  count: items.length,
  pageInfo: pageInfo(items, page, size),
});

export const genericLog = {
  _id: "log-1",
  id: "log-1",
  action: "Demo action",
  message: "Dummy backend event generated for portfolio walkthrough.",
  createdAt: "2026-05-21T10:00:00.000Z",
  Author: demoUser,
  author: demoUser,
};

export const categories = [
  { _id: "cat-1", categoryId: "cat-1", category_name: "Food", categoryName: "Food", name: "Food", categoryPrefix: "FD", isActive: true, vertical: "FMCG", verticalId: "vertical-1" },
  { _id: "cat-2", categoryId: "cat-2", category_name: "Beverages", categoryName: "Beverages", name: "Beverages", categoryPrefix: "BV", isActive: true, vertical: "FMCG", verticalId: "vertical-1" },
  { _id: "cat-3", categoryId: "cat-3", category_name: "Household", categoryName: "Household", name: "Household", categoryPrefix: "HH", isActive: true, vertical: "FMCG", verticalId: "vertical-1" },
];

export const subCategories = [
  { _id: "subcat-1", subCategoryId: "subcat-1", subCategoryName: "Noodles", name: "Noodles", categoryId: "cat-1", isActive: true },
  { _id: "subcat-2", subCategoryId: "subcat-2", subCategoryName: "Cooking Oil", name: "Cooking Oil", categoryId: "cat-1", isActive: true },
];

export const brands = [
  { _id: "brand-1", brandId: "brand-1", brandName: "Golden Penny", name: "Golden Penny", isActive: true },
  { _id: "brand-2", brandId: "brand-2", brandName: "Alerzo Demo", name: "Alerzo Demo", isActive: true },
];

export const manufacturers = [
  { _id: "mfr-1", manufacturerId: "mfr-1", manufacturerName: "Flour Mills Nigeria", name: "Flour Mills Nigeria", isActive: true },
  { _id: "mfr-2", manufacturerId: "mfr-2", manufacturerName: "Demo Foods Ltd", name: "Demo Foods Ltd", isActive: true },
];

export const verticals = [
  { _id: "vertical-1", verticalId: "vertical-1", verticalName: "FMCG", name: "FMCG", isActive: true },
  { _id: "vertical-2", verticalId: "vertical-2", verticalName: "Pharma", name: "Pharma", isActive: true },
];

export const landmarks = [
  {
    landmarkId: "landmark-1",
    _id: "landmark-1",
    landmarkName: "Dugbe Market",
    lat: 7.387,
    long: 3.896,
    isActive: true,
    Warehouse: warehouses[0],
    LGA: { lgaId: "lga-1", lgaName: "Ibadan North" },
  },
  {
    landmarkId: "landmark-2",
    _id: "landmark-2",
    landmarkName: "Ojoo Junction",
    lat: 7.432,
    long: 3.912,
    isActive: true,
    Warehouse: warehouses[0],
    LGA: { lgaId: "lga-1", lgaName: "Ibadan North" },
  },
];

export const lgas = [
  { lgaId: "lga-1", _id: "lga-1", lgaName: "Ibadan North", cityId: "city-1", stateId: "state-1", isActive: true },
  { lgaId: "lga-2", _id: "lga-2", lgaName: "Ikeja", cityId: "city-2", stateId: "state-2", isActive: true },
];

export const demoTransfer = {
  _id: "transfer-1",
  id: "transfer-1",
  referenceId: "TRF-001",
  status: "pending",
  fromWarehouseId: "warehouse-1",
  toWarehouseId: "warehouse-2",
  fromWarehouseDetails: warehouses[0],
  toWarehouseDetails: warehouses[1],
  driverDetails: demoUser,
  stockControllerDetails: demoUser,
  vehicleNumber: "ABC123DE",
  createdAt: "2026-05-20T09:00:00.000Z",
  stockProducts: products.map((p) => ({ ...p, value: 10 })),
  stock: products.map((p) => ({ productId: p._id, value: 10 })),
};

export const demoProcurement = {
  _id: "procurement-1",
  id: "procurement-1",
  referenceId: "PCM-001",
  status: "pending",
  warehouseId: "warehouse-1",
  driverName: "Demo Driver",
  vehicleNumber: "ABC123DE",
  distributor: "Demo Distributor",
  manufacturer: "Flour Mills Nigeria",
  comment: "Demo procurement",
  invoiceNumber: "INV-001",
  waybillNumber: "WB-001",
  createdAt: "2026-05-20T09:00:00.000Z",
  stockProducts: products.map((p) => ({ ...p, value: 50 })),
  stock: products.map((p) => ({ productId: p._id, value: 50 })),
  stockControllerDetails: demoUser,
};

export const demoIncident = {
  _id: "incident-1",
  id: "incident-1",
  referenceId: "INC-001",
  status: "pending",
  warehouseId: "warehouse-1",
  incidentType: "damage",
  reason: "Demo incident reason",
  comment: "Demo incident comment",
  userRole: "Inventory Officer",
  userDetails: demoUser,
  warehouseDetails: warehouses[0],
  createdAt: "2026-05-20T09:00:00.000Z",
  stockProducts: products.map((p) => ({ ...p, value: 5 })),
  stock: products.map((p) => ({ productId: p._id, value: 5 })),
};

export const demoPurchaseRequisition = {
  _id: "pr-1",
  id: "pr-1",
  referenceId: "PR-001",
  status: "pending",
  warehouseId: "warehouse-1",
  warehouseName: "Ibadan Main Warehouse",
  reason: "Demo restock",
  sellerId: "seller-1",
  sellerDetails: sellers[0],
  requestedBy: "Demo Admin",
  createdAt: "2026-05-20T09:00:00.000Z",
  products: products.map((p) => ({ productId: p._id, quantity: 100, price: p.price })),
};

export const demoPurchaseOrder = {
  _id: "po-1",
  id: "po-1",
  referenceId: "PO-001",
  purchaseRequisitionReferenceId: "PR-001",
  status: "pending",
  totalAmount: 320000,
  estimatedArrival: "2026-05-25T00:00:00.000Z",
  reason: "Demo purchase order",
  leadTime: 3,
  paymentDetails: { creditBalance: 500000 },
  createdAt: "2026-05-20T09:00:00.000Z",
};

export const demoInStoreTransaction = {
  _id: "ist-1",
  id: "ist-1",
  referenceId: "IST-001",
  status: "transaction_pending",
  warehouseId: "warehouse-1",
  warehouseDetails: warehouses[0],
  createdAt: "2026-05-20T09:00:00.000Z",
  products: products.map((p) => ({ ...p, quantity: 10 })),
};

export const demoDeliveryPlan = {
  _id: "plan-1",
  id: "plan-1",
  planId: "plan-1",
  referenceId: "PLN-001",
  status: "unassigned",
  warehouseId: "warehouse-1",
  warehouse: warehouses[0],
  vehicle: vehicles[0],
  driver: demoUser,
  orders,
  createdAt: "2026-05-20T09:00:00.000Z",
};

export const demoVehicleRequest = {
  _id: "vr-1",
  id: "vr-1",
  referenceId: "VR-001",
  status: "pending",
  warehouseId: "warehouse-1",
  requestedBy: demoUser,
  createdAt: "2026-05-20T09:00:00.000Z",
};

export const demoTerminal = {
  terminalId: "terminal-1",
  _id: "terminal-1",
  serialNumber: "SN-DEMO-001",
  posTerminalId: "POS-001",
  referenceId: "TRM-001",
  provider: "Demo POS Provider",
  posVariant: "standard",
  status: "unassigned",
  userId: null,
  isActive: true,
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
};

export const demoDeliveryFee = {
  _id: "fee-1",
  id: "fee-1",
  referenceId: "DF-001",
  deliveryFeeName: "Standard Delivery Fee",
  amount: 500,
  feeType: "flat",
  status: "ACTIVE",
  platform: "ADMIN_WEB",
  warehouseId: "warehouse-1",
  warehouse: warehouses[0],
  verticalId: "vertical-1",
  verticalName: "FMCG",
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
  rangeConstraints: [],
};

export const demoProcessingFee = {
  _id: "pfee-1",
  id: "pfee-1",
  referenceId: "PF-001",
  paymentProvider: "PAYSTACK",
  paymentMethod: "CARD",
  chargeType: "percentage",
  charge: 150,
  minChargePercent: 1,
  paymentMode: "online",
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
  constraints: { maxAmount: 2000, minAmount: 100 },
};

export const demoDistributor = {
  _id: "distributor-1",
  id: "distributor-1",
  distributorId: "distributor-1",
  distributorName: "Demo Distributor Ltd",
  distributorType: "primary",
  address: "Demo Distributor Address",
  contactName: "Distributor Contact",
  email: "distributor@example.com",
  phoneNumber: "+2348090005555",
  bvn: "12345678901",
  cacNumber: "RC-DEMO-001",
  logo: null,
  verticalId: "vertical-1",
  vertical: "FMCG",
  isActive: true,
  paymentType: "credit",
  categoryIds: ["cat-1"],
  categories: ["Food"],
  registrationPrefix: "DD",
  creditTerm: 30,
  Warehouses: [warehouses[0]],
  cityId: "city-1",
  City: { cityId: "city-1", cityName: "Ibadan", State: { stateId: "state-1", stateName: "Oyo" } },
};

export const demoInventoryItem = {
  _id: "inv-1",
  productId: "product-1",
  stockValue: 240,
  availableStock: 200,
  status: "in_stock",
  product: {
    ...products[0],
    displayTitle: "Golden Penny Noodles 70g",
    product_SKU: "ALZ-NDL-70",
    images: [{ imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246" }],
  },
  sellerDetails: [{ _id: "seller-1", sellerName: "Demo FMCG Seller" }],
  verticalName: "FMCG",
};

export const demoRoute = {
  _id: "route-1",
  id: "route-1",
  routeId: "route-1",
  referenceId: "RT-001",
  routeName: "Ibadan Demo Route",
  status: "Active",
  driverName: demoUser.fullName,
  vehicleNumber: vehicles[0].vehicleNumber,
  vehicleType: vehicles[0].vehicleType,
  ordersCount: orders.length,
  ordercount: orders.length,
  eta: "2h 15m",
  actualtime: "2h 05m",
  routeDate: "2026-05-21T08:00:00.000Z",
  dispatchTime: "2026-05-21T08:15:00.000Z",
  completedTime: "2026-05-21T10:20:00.000Z",
  workingTime: "2h 15m",
  distance: "18.4 km",
  warehouse: warehouses[0],
  Warehouse: warehouses[0],
  vehicle: vehicles[0],
  Vehicle: vehicles[0],
  driver: demoUser,
  Driver: demoUser,
  salesRepresentative: demoUser,
  salesDriver: demoUser,
  orders,
  lat: 7.3775,
  long: 3.947,
};

export const demoOrderPerformance = {
  orderReceived: 128,
  orderCancelled: 6,
  orderReturned: 4,
  totalTrips: 42,
};

export const demoSalesBySegment = [
  {
    segment: "Active Customer",
    totalSales: 2500000,
    totalOrders: 85,
    totalCustomers: 40,
    percentageOfTotalSales: 45,
  },
  {
    segment: "Inactive Customer",
    totalSales: 1200000,
    totalOrders: 32,
    totalCustomers: 18,
    percentageOfTotalSales: 22,
  },
  {
    segment: "Dormant Customer",
    totalSales: 900000,
    totalOrders: 21,
    totalCustomers: 12,
    percentageOfTotalSales: 16,
  },
  {
    segment: "Churned Customer",
    totalSales: 950000,
    totalOrders: 19,
    totalCustomers: 9,
    percentageOfTotalSales: 17,
  },
];

export const demoInventoryMetrics = {
  inventoryValuation: 12500000,
  inventoryCount: 1840,
};

export const demoStockByCategory = warehouses.map((warehouse) => ({
  warehouseName: warehouse.warehouseName,
  categories: categories.slice(0, 3).map((category, index) => ({
    categoryName: category.categoryName,
    stockValuation: 1800000 + index * 350000,
    stockCount: 240 + index * 80,
  })),
}));

export const demoTotalSales = warehouses.map((warehouse, index) => ({
  warehouseId: warehouse.warehouseId,
  warehouseName: warehouse.warehouseName,
  totalSales: 1500000 + index * 750000,
}));

export const demoTopSellingProducts = products.map((product, index) => ({
  productId: product.productId,
  productSKU: product.sku,
  displayTitle: product.displayName,
  totalSales: product.price * (40 - index * 10),
  quantitySold: 40 - index * 10,
}));

export const demoTopProductsByCancellation = products.map((product, index) => ({
  productId: product.productId,
  productSKU: product.sku,
  displayTitle: product.displayName,
  numberOfTimesCancelled: 2 + index,
  quantityCancelled: 5 + index,
  quantitySold: 40 - index * 10,
  imageUrl: product.imageUrl,
  cancelledValuation: product.price * (5 + index),
}));

export const demoSalesTrend = [
  {
    date: "2026-05-19",
    products: products.map((product) => ({
      product: product.displayName,
      totalSales: product.price * 20,
    })),
  },
  {
    date: "2026-05-20",
    products: products.map((product) => ({
      product: product.displayName,
      totalSales: product.price * 28,
    })),
  },
  {
    date: "2026-05-21",
    products: products.map((product) => ({
      product: product.displayName,
      totalSales: product.price * 35,
    })),
  },
];

export const demoStockForecastNodes = products.map((product, index) => ({
  productId: product.productId,
  warehouseId: warehouses[0].warehouseId,
  product: {
    product_SKU: product.sku,
    displayTitle: product.displayName,
  },
  date: "2026-05-21",
  fcMonthlyAvg: 120 + index * 15,
  fcDemand: 90 + index * 10,
  leadTime: 3,
  quantityToOrder: 50 + index * 5,
  quantity: 240 - index * 20,
  stockValue: product.price * (240 - index * 20),
  Fill_Rate: 0.92,
  orderBy: "Demo Admin",
  warehouseDetails: warehouses[0],
}));

export const demoCoupon = {
  _id: "coupon-1",
  id: "coupon-1",
  couponName: "Demo Welcome Coupon",
  couponCode: "DEMO10",
  couponDescription: "10% off demo orders",
  platformApplicable: "ADMIN_WEB",
  stateId: "state-1",
  cityId: "city-1",
  warehouseId: "warehouse-1",
  discountType: "percentage",
  discount: 10,
  customerSegement: "Active Customer",
  usesPerCoupon: 100,
  usesPerCustomer: 1,
  cartValue: 5000,
  startDate: "2026-01-01",
  endDate: "2026-12-31",
  termsAndCondition: "Demo terms and conditions",
  status: "ACTIVE",
  createdAt: "2026-01-01T00:00:00.000Z",
};

const bannerImageVersions = [
  { language: "en", imageUrl: UNSPLASH.banner },
  { language: "yo", imageUrl: UNSPLASH.store },
];

export const demoBanner = {
  _id: "banner-1",
  id: "banner-1",
  bannerName: "Summer Promo Banner",
  title: "Summer Promo Banner",
  image: UNSPLASH.banner,
  imageUrl: UNSPLASH.banner,
  isActive: true,
  status: "ACTIVE",
  redirectTo: "/products",
  redirectType: "internal",
  redirectValue: "product-1",
  position: "home_top",
  category: "Food",
  state: "Oyo",
  city: "Ibadan",
  warehouse: "Ibadan Main Warehouse",
  customerSegment: "Active Customer",
  platform: "ADMIN_WEB",
  startDate: "2026-01-01T00:00:00.000Z",
  endDate: "2026-12-31T23:59:59.000Z",
  duration: 30,
  priority: 1,
  params: [{ name: "campaign", value: "demo-summer" }],
  desktopVersion: bannerImageVersions,
  mobileVersion: bannerImageVersions,
  createdAt: "2026-01-01T00:00:00.000Z",
};

export const demoBundle = {
  _id: "bundle-1",
  id: "bundle-1",
  bundleName: "Demo Bundle Pack",
  bundleType: "STANDARD",
  description: "Demo bundle for portfolio walkthrough",
  bundleCities: [{ bundleCityId: "city-1", minimumQuantity: 1, warehouseId: "warehouse-1" }],
  bundleProducts,
  promotedProducts: bundleProducts.slice(0, 1),
  desktopVersion: bannerImageVersions,
  mobileVersion: bannerImageVersions,
  sector: { sectorId: "sector-1", sectorName: "Demo Sector" },
};

export const demoPromotion = {
  _id: "promo-1",
  id: "promo-1",
  promotionName: "Demo Promotion",
  promotionPlatform: "ADMIN_WEB",
  discountType: "percentage",
  discount: 15,
  brands: ["Golden Penny"],
  categories: ["Food"],
  cityId: "city-1",
  city: "Ibadan",
  state: "Oyo",
  stateId: "state-1",
  warehouseId: "warehouse-1",
  warehouse: "Ibadan Main Warehouse",
  status: "ACTIVE",
  startDate: "2026-01-01",
  endDate: "2026-12-31",
  vertical: "FMCG",
  verticalId: "vertical-1",
  customerSegments: [],
};

export const demoTodo = {
  _id: "todo-1",
  id: "todo-1",
  todoUrl: "/dashboard/orders/order-1",
  user_id: "user-1",
  todoType: "Order",
  action: "validate_order",
  nextAction: "dispatch_order",
  referenceId: "ALZ-ORD-1001",
  status: "pending",
  updatedAt: "2026-05-21T10:00:00.000Z",
  createdAt: "2026-05-21T10:00:00.000Z",
  object_id: "order-1",
  additionalRemarks: "Dugbe Market",
  warehouseId: "warehouse-1",
};

export const demoVisitation = {
  visitationId: "visit-1",
  _id: "visit-1",
  userId: "user-1",
  user: demoUser,
  customerId: "customer-1",
  Customer: customers[0],
  referenceId: "VIS-001",
  createdAt: "2026-05-20T09:00:00.000Z",
  updatedAt: "2026-05-20T09:00:00.000Z",
};

export const demoUom = {
  _id: "uom-1",
  uomId: "uom-1",
  uomName: "Carton",
  uomSapId: "CTN",
  isActive: true,
};

export const demoBackOrderItem = {
  _id: "bo-1",
  id: "bo-1",
  referenceId: "BO-001",
  status: "pending",
  customerId: "customer-1",
  customer: customers[0],
  warehouseId: "warehouse-1",
  warehouse: warehouses[0],
  createdAt: "2026-05-20T09:00:00.000Z",
  items: products.map((p) => ({ ...p, quantity: 5 })),
};

// ─── Zeebly Admin (cap-admin-web) fixtures ──────────────────────────

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const okResponse = (data: unknown) => ({
  data,
  status: true,
  statusCode: 200,
  message: "Success",
});

export const zeeblyAdminUser = {
  _id: "zeebly-admin-1",
  fullName: "Zeebly Admin",
  staffId: "ZA-001",
  phoneNumber: "08012345678",
  email: "admin@zeebly.com",
  roleId: "zeebly-role-1",
  roleName: "Super Admin",
  isFirstTimeLogin: false,
  status: "ACTIVE",
  profilePicture: [{ url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200" }],
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-05-20T00:00:00.000Z",
};

export const zeeblyAdminUsers = [
  zeeblyAdminUser,
  {
    _id: "zeebly-admin-2",
    fullName: "Demo Operations",
    staffId: "ZA-002",
    phoneNumber: "08098765432",
    email: "ops@zeebly.com",
    roleId: "zeebly-role-2",
    roleName: "Operations Manager",
    isFirstTimeLogin: false,
    status: "ACTIVE",
    createdAt: "2026-02-01T00:00:00.000Z",
    updatedAt: "2026-05-19T00:00:00.000Z",
  },
  {
    _id: "zeebly-admin-3",
    fullName: "New Staff",
    staffId: "ZA-003",
    phoneNumber: "08055556666",
    email: "new@zeebly.com",
    roleId: "zeebly-role-3",
    roleName: "Viewer",
    isFirstTimeLogin: true,
    status: "ACTIVE",
    createdAt: "2026-05-15T00:00:00.000Z",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
];

export const zeeblyRoles = [
  {
    id: "zeebly-role-1",
    roleName: "Super Admin",
    permissions: [
      { id: "perm-1", permissionName: "ALL", permissionDescription: "Full system access" },
    ],
  },
  {
    id: "zeebly-role-2",
    roleName: "Operations Manager",
    permissions: [
      { id: "perm-2", permissionName: "MANAGE_CENTERS", permissionDescription: "Manage centres" },
      { id: "perm-3", permissionName: "VIEW_ORDERS", permissionDescription: "View orders" },
      { id: "perm-4", permissionName: "MANAGE_PARTNERS", permissionDescription: "Manage partners" },
    ],
  },
  {
    id: "zeebly-role-3",
    roleName: "Viewer",
    permissions: [
      { id: "perm-5", permissionName: "VIEW_DASHBOARD", permissionDescription: "View dashboard" },
    ],
  },
];

export const zeeblyPermissions = [
  { id: "perm-1", permissionName: "ALL", permissionDescription: "Full system access" },
  { id: "perm-2", permissionName: "MANAGE_CENTERS", permissionDescription: "Manage centres" },
  { id: "perm-3", permissionName: "VIEW_ORDERS", permissionDescription: "View orders" },
  { id: "perm-4", permissionName: "MANAGE_PARTNERS", permissionDescription: "Manage partners" },
  { id: "perm-5", permissionName: "VIEW_DASHBOARD", permissionDescription: "View dashboard" },
  { id: "perm-6", permissionName: "MANAGE_INVENTORY", permissionDescription: "Manage inventory" },
];

export const zeeblyCenters = [
  {
    id: "centre-1",
    centre_id: "CEN-001",
    centre_name: "Ibadan Main Centre",
    centre_address: "42 Ring Road, Ibadan, Oyo State",
    region: "South West",
    business_name: "Ibadan Main Ventures",
    account_number: "0123456789",
    serial_number: "SN-001",
    credit_limit: 5000000,
    credit_balance: 1250000,
    wallet_balance: 3400000,
    total_balance: 4650000,
    rep: [{ id: "rep-1", serial_number: "REP-001", representative_id: "REP-001", first_name: "Chidi", last_name: "Okonkwo", email: "chidi@example.com", phone_number: "08011111111", center: [{ centre_id: "CEN-001", centre_name: "Ibadan Main Centre" }], status: "ACTIVE", created_at: "2026-01-15T00:00:00.000Z", updated_at: "2026-05-20T00:00:00.000Z" }],
    partner: { id: "partner-1", partner_name: "Ibadan Partner Ltd", email: "partner1@example.com", phone_number: "08022222222" },
    created_at: "2026-01-15T00:00:00.000Z",
    updated_at: "2026-05-20T00:00:00.000Z",
    state: "Oyo",
  },
  {
    id: "centre-2",
    centre_id: "CEN-002",
    centre_name: "Lagos Island Centre",
    centre_address: "15 Marina Street, Lagos Island",
    region: "South West",
    business_name: "Lagos Island Enterprises",
    account_number: "0987654321",
    serial_number: "SN-002",
    credit_limit: 8000000,
    credit_balance: 2100000,
    wallet_balance: 5200000,
    total_balance: 7300000,
    rep: [{ id: "rep-2", serial_number: "REP-002", representative_id: "REP-002", first_name: "Bola", last_name: "Adebayo", email: "bola@example.com", phone_number: "08033333333", center: [{ centre_id: "CEN-002", centre_name: "Lagos Island Centre" }], status: "ACTIVE", created_at: "2026-02-01T00:00:00.000Z", updated_at: "2026-05-19T00:00:00.000Z" }],
    partner: { id: "partner-2", partner_name: "Lagos Distributors Ltd", email: "partner2@example.com", phone_number: "08044444444" },
    created_at: "2026-02-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    state: "Lagos",
  },
  {
    id: "centre-3",
    centre_id: "CEN-003",
    centre_name: "Abuja Central Centre",
    centre_address: "8 Constitution Avenue, Abuja FCT",
    region: "North Central",
    business_name: "Abuja Central Ltd",
    account_number: "0555123456",
    serial_number: "SN-003",
    credit_limit: 3000000,
    credit_balance: 800000,
    wallet_balance: 1900000,
    total_balance: 2700000,
    rep: [{ id: "rep-3", serial_number: "REP-003", representative_id: "REP-003", first_name: "Aisha", last_name: "Mohammed", email: "aisha@example.com", phone_number: "08055555555", center: [{ centre_id: "CEN-003", centre_name: "Abuja Central Centre" }], status: "ACTIVE", created_at: "2026-03-01T00:00:00.000Z", updated_at: "2026-05-18T00:00:00.000Z" }],
    partner: { id: "partner-3", partner_name: "Abuja Gateway Partners", email: "partner3@example.com", phone_number: "08066666666" },
    created_at: "2026-03-01T00:00:00.000Z",
    updated_at: "2026-05-18T00:00:00.000Z",
    state: "Abuja FCT",
  },
];

export const zeeblyPartners = [
  {
    id: "partner-1",
    partner_id: "PTN-001",
    partner_name: "Ibadan Partner Ltd",
    first_name: "Kunle",
    last_name: "Adebayo",
    email: "partner1@example.com",
    phone_number: "08022222222",
    centre_name: "Ibadan Main Centre",
    centre: [{ centre_id: "CEN-001", centre_name: "Ibadan Main Centre" }],
    status: "ACTIVE",
    is_first_time_login: false,
    role_meta: { role_id: "partner-role-1", role_name: "Partner Admin" },
    centre_info: [{ id: "centre-1", centre_id: "CEN-001", centre_name: "Ibadan Main Centre", centre_address: "42 Ring Road, Ibadan, Oyo State", region: "South West", business_name: "Ibadan Main Ventures", account_number: "0123456789", serial_number: "SN-001", credit_limit: 5000000, credit_balance: 1250000, wallet_balance: 3400000, total_balance: 4650000, state: "Oyo", rep: [{ id: "rep-1", serial_number: "REP-001", representative_id: "REP-001", first_name: "Chidi", last_name: "Okonkwo", email: "chidi@example.com", phone_number: "08011111111", status: "ACTIVE", role_meta: { role_id: "rep-role-1", role_name: "Sales Rep" }, created_at: "2026-01-15T00:00:00.000Z", updated_at: "2026-05-20T00:00:00.000Z" }], created_at: "2026-01-15T00:00:00.000Z", updated_at: "2026-05-20T00:00:00.000Z" }],
    created_at: "2026-01-20T00:00:00.000Z",
    updated_at: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "partner-2",
    partner_id: "PTN-002",
    partner_name: "Lagos Distributors Ltd",
    first_name: "Femi",
    last_name: "Ogunlade",
    email: "partner2@example.com",
    phone_number: "08044444444",
    centre_name: "Lagos Island Centre",
    centre: [{ centre_id: "CEN-002", centre_name: "Lagos Island Centre" }],
    status: "ACTIVE",
    is_first_time_login: false,
    role_meta: { role_id: "partner-role-2", role_name: "Partner Admin" },
    centre_info: [{ id: "centre-2", centre_id: "CEN-002", centre_name: "Lagos Island Centre", centre_address: "15 Marina Street, Lagos Island", region: "South West", business_name: "Lagos Island Enterprises", account_number: "0987654321", serial_number: "SN-002", credit_limit: 8000000, credit_balance: 2100000, wallet_balance: 5200000, total_balance: 7300000, state: "Lagos", rep: [{ id: "rep-2", serial_number: "REP-002", representative_id: "REP-002", first_name: "Bola", last_name: "Adebayo", email: "bola@example.com", phone_number: "08033333333", status: "ACTIVE", role_meta: { role_id: "rep-role-2", role_name: "Senior Sales Rep" }, created_at: "2026-02-01T00:00:00.000Z", updated_at: "2026-05-19T00:00:00.000Z" }], created_at: "2026-02-01T00:00:00.000Z", updated_at: "2026-05-19T00:00:00.000Z" }],
    created_at: "2026-02-05T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
  },
];

export const zeeblyReps = [
  {
    id: "rep-1",
    serial_number: "REP-001",
    representative_id: "REP-001",
    first_name: "Chidi",
    last_name: "Okonkwo",
    email: "chidi@example.com",
    phone_number: "08011111111",
    center: [{ centre_id: "CEN-001", centre_name: "Ibadan Main Centre", id: "centre-1" }],
    partner_id: "partner-1",
    status: "ACTIVE",
    role_meta: { role_id: "rep-role-1", role_name: "Sales Rep" },
    created_at: "2026-01-15T00:00:00.000Z",
    updated_at: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "rep-2",
    serial_number: "REP-002",
    representative_id: "REP-002",
    first_name: "Bola",
    last_name: "Adebayo",
    email: "bola@example.com",
    phone_number: "08033333333",
    center: [{ centre_id: "CEN-002", centre_name: "Lagos Island Centre", id: "centre-2" }],
    partner_id: "partner-2",
    status: "ACTIVE",
    role_meta: { role_id: "rep-role-2", role_name: "Senior Sales Rep" },
    created_at: "2026-02-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
  },
  {
    id: "rep-3",
    serial_number: "REP-003",
    representative_id: "REP-003",
    first_name: "Aisha",
    last_name: "Mohammed",
    email: "aisha@example.com",
    phone_number: "08055555555",
    center: [{ centre_id: "CEN-003", centre_name: "Abuja Central Centre", id: "centre-3" }],
    partner_id: "partner-3",
    status: "ACTIVE",
    role_meta: { role_id: "rep-role-3", role_name: "Sales Rep" },
    created_at: "2026-03-01T00:00:00.000Z",
    updated_at: "2026-05-18T00:00:00.000Z",
  },
];

export const zeeblyRepRoles = [
  { id: "rep-role-1", roleName: "Sales Rep", permissions: [{ id: "perm-5", permissionName: "VIEW_DASHBOARD", permissionDescription: "View dashboard" }] },
  { id: "rep-role-2", roleName: "Senior Sales Rep", permissions: [{ id: "perm-5", permissionName: "VIEW_DASHBOARD", permissionDescription: "View dashboard" }] },
  { id: "rep-role-3", roleName: "Sales Rep", permissions: [{ id: "perm-5", permissionName: "VIEW_DASHBOARD", permissionDescription: "View dashboard" }] },
];

export const zeeblyOrders = zeeblyCenters.map((c, ci) => ({
  _id: `zeebly-order-${ci + 1}`,
  id: `zeebly-order-${ci + 1}`,
  orderId: `ZBL-ORD-${String(ci + 1).padStart(4, "0")}`,
  total_quantity: 15 + ci * 5,
  total_amount: 125000 + ci * 45000,
  total_discount_amount: 2500 + ci * 1000,
  sub_total: 127500 + ci * 46000,
  vat: 0,
  customer_name: `Customer ${ci + 1}`,
  user_name: "Demo Admin",
  sap_order_id: `SAP-ORD-${ci + 1}`,
  notes: "Demo order",
  order_date: daysAgo(ci + 1),
  created_at: daysAgo(ci + 1),
  updated_at: daysAgo(ci),
  centre_id: c.centre_id,
  center: { centre_id: c.centre_id, centre_name: c.centre_name, centre_address: c.centre_address, account_number: c.account_number },
  partner_id: `partner-${ci + 1}`,
  partner_metadata: {},
  center_metadata: {},
  partner: {
    partner_name: zeeblyPartners[ci]?.partner_name || "Demo Partner",
    partner_id: `partner-${ci + 1}`,
    email: `partner${ci + 1}@example.com`,
    phone_number: `0802222222${ci + 1}`,
  },
  items: [
    {
      id: `item-${ci + 1}-1`,
      product_id: "zbl-prod-1",
      productId: "zbl-prod-1",
      quantity: 10,
      quantity_left: 2,
      quantity_delivered: 8,
      total_amount: 85000,
      amount: 8500,
      is_new: true,
      product_line: "Beverages",
      sap_name: "Demo Product",
      brand: "Demo Brand",
      status: "delivered",
      product: { name: "Demo Beverage Pack", description: "Assorted beverage pack" },
    },
  ],
  is_deleted: false,
  current_version: 1,
  status: ci === 0 ? "completed" : ci === 1 ? "processing" : "pending",
  display_status: ci === 0 ? "completed" : ci === 1 ? "processing" : "pending",
  previous_states: [],
  manually_locked: false,
  order_locked: false,
  min_delivery_days: 1,
  max_delivery_days: 3,
  sla_minimum_load_req: 10000,
  center_discount: 0,
  center_discount_table: [],
}));

export const zeeblyDashboardRecentTransactions = [
  { id: "txn-1", reference: "TXN-001", customer: "Mama T Store", amount: 15000, type: "order_payment", status: "completed", created_at: daysAgo(0) },
  { id: "txn-2", reference: "TXN-002", customer: "Lagos Retail Hub", amount: 28500, type: "order_payment", status: "completed", created_at: daysAgo(0) },
  { id: "txn-3", reference: "TXN-003", customer: "University Kiosk", amount: 7500, type: "wallet_funding", status: "pending", created_at: daysAgo(1) },
  { id: "txn-4", reference: "TXN-004", customer: "Mama T Store", amount: 42000, type: "order_payment", status: "completed", created_at: daysAgo(1) },
  { id: "txn-5", reference: "TXN-005", customer: "Lagos Retail Hub", amount: 12000, type: "payout", status: "completed", created_at: daysAgo(2) },
];

export const zeeblyInventoryItems = [
  {
    id: "zbl-inv-1",
    name: "Demo Beverage Pack",
    description: "Assorted beverage pack with 24 units",
    is_new: true,
    amount: 8500,
    unit: "Pack",
    per_item: 354,
    uom: "PACK",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    brand: "Demo Brand",
    product_line: "Beverages",
    class_type: "Fast Moving",
    color: "Blue",
    category: "Beverages",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-05-20T00:00:00.000Z",
    sap_id: "SAP-BEV-001",
    amount_sold: 240,
    quantity_in_stock: 480,
    min_order_quantity: 10,
    out_of_stock_status: false,
    locked_status: false,
    is_deleted: false,
    images: [{ url: "https://images.unsplash.com/photo-1556745757-8d76bdb6984b?w=300" }],
  },
  {
    id: "zbl-inv-2",
    name: "Premium Cooking Oil 5L",
    description: "Premium quality vegetable cooking oil",
    is_new: false,
    amount: 12500,
    unit: "Carton",
    per_item: 2500,
    uom: "CARTON",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    brand: "Premium Brands",
    product_line: "Cooking Oil",
    class_type: "Medium Moving",
    color: "Yellow",
    category: "Groceries",
    created_at: "2026-01-15T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    sap_id: "SAP-OIL-001",
    amount_sold: 120,
    quantity_in_stock: 240,
    min_order_quantity: 5,
    out_of_stock_status: false,
    locked_status: false,
    is_deleted: false,
    images: [{ url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300" }],
  },
  {
    id: "zbl-inv-3",
    name: "Instant Noodles 70g Carton",
    description: "Popular instant noodles, 50 packs per carton",
    is_new: false,
    amount: 4500,
    unit: "Carton",
    per_item: 90,
    uom: "CARTON",
    valid_from: "2026-01-01",
    valid_to: "2026-12-31",
    brand: "Golden Penny",
    product_line: "Noodles",
    class_type: "Fast Moving",
    color: "Yellow",
    category: "Food",
    created_at: "2026-01-10T00:00:00.000Z",
    updated_at: "2026-05-20T00:00:00.000Z",
    sap_id: "SAP-NDL-001",
    amount_sold: 500,
    quantity_in_stock: 1000,
    min_order_quantity: 20,
    out_of_stock_status: false,
    locked_status: false,
    is_deleted: false,
    images: [{ url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300" }],
  },
];

export const zeeblyInventoryCategories = [
  { name: "Beverages", count: 15 },
  { name: "Food", count: 28 },
  { name: "Groceries", count: 12 },
  { name: "Household", count: 9 },
  { name: "Personal Care", count: 7 },
];

export const zeeblyNotifications = Array.from({ length: 10 }, (_, i) => ({
  id: `notif-${i + 1}`,
  title: i === 0 ? "New Order Alert" : i === 1 ? "Payment Received" : i === 2 ? "Low Stock Warning" : `Notification ${i + 1}`,
  message: i === 0 ? "New order #ZBL-ORD-0001 has been placed" : i === 1 ? "Payment of ₦15,000 received for order #ZBL-ORD-0001" : i === 2 ? "Product 'Demo Beverage Pack' is running low on stock" : `This is demo notification ${i + 1}`,
  status: i < 3 ? "unread" : "read",
  created_at: daysAgo(i),
}));

export const zeeblyAuditLog = (type: string, index: number) => {
  const base = {
    id: `${type}-audit-${index + 1}`,
    action_type: ["CREATE", "UPDATE", "DELETE", "LOGIN", "EXPORT"][index % 5],
    description: ["Created new centre", "Updated partner details", "Deleted order", "User logged in", "Exported report"][index % 5],
    action_date: daysAgo(index),
    created_at: daysAgo(index),
    updated_at: daysAgo(index),
  };
  if (type === "admin") return { ...base, admin_id: `zeebly-admin-${(index % 3) + 1}`, admin_name: zeeblyAdminUsers[index % 3].fullName, admin_email: zeeblyAdminUsers[index % 3].email };
  if (type === "partner") return { ...base, partner_id: `partner-${(index % 2) + 1}`, partner_name: zeeblyPartners[index % 2].partner_name, partner_email: zeeblyPartners[index % 2].email, centre_id: `CEN-${String((index % 3) + 1).padStart(3, "0")}`, centre_name: zeeblyCenters[index % 3].centre_name };
  return { ...base, rep_id: `rep-${(index % 3) + 1}`, rep_name: `${zeeblyReps[index % 3].first_name} ${zeeblyReps[index % 3].last_name}`, rep_email: zeeblyReps[index % 3].email, centre_id: `CEN-${String((index % 3) + 1).padStart(3, "0")}`, centre_name: zeeblyCenters[index % 3].centre_name };
};

export const zeeblyPaginated = (items: unknown[], page = 1, limit = 10) => ({
  data: {
    total_count: items.length,
    total_items: items.length,
    limit,
    page,
    total_pages: Math.max(1, Math.ceil(items.length / limit)),
    serial_no: (page - 1) * limit + 1,
    has_previous_page: page > 1,
    has_next_page: page < Math.ceil(items.length / limit),
    next_page: page < Math.ceil(items.length / limit) ? page + 1 : null,
    previous_page: page > 1 ? page - 1 : null,
  },
  status: true,
  statusCode: 200,
  message: "Success",
});

export const zeeblyOkMutation = (id: string) => okResponse({ id });

export const zeeblyDashboardStat = {
  totalCount: 120,
  totalAmount: 4500000,
  previous: 95,
  previousTotalAmount: 3800000,
  percent_change_count: 26.3,
  percent_change_amount: 18.4,
};

